import type { Metadata } from 'next'
import '@shared/styles/globals.css'
import React from 'react'
import {HeaderWidget} from '@widgets/header/header-widget'
import {primaryFont} from '@shared/configs/font.config'



export const metadata: Metadata = {
  title: 'bull-sheet-icons',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<React.PropsWithChildren> = ({children}) => {
  return (
    <html lang="en">
      <body className={primaryFont.className}>
        <HeaderWidget/>
        <div className="content-container">
          {children}
        </div>

      </body>
    </html>
  )
}

export default RootLayout
