import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@shared/styles/globals.css'
import React from 'react'
import {HeaderWidget} from '@widgets/header/header-widget'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<React.PropsWithChildren> = ({children}) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeaderWidget/>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
