export {errorIcon} from './functions/error-icon'
export {linkedinIcon} from './functions/linkedin-icon'
export {telegramIcon} from './functions/telegram-icon'
export {instagramIcon} from './functions/instagram-icon'
export {facebookIcon} from './functions/facebook-icon'
export {okIcon} from './functions/ok-icon'
export {skypeIcon} from './functions/skype-icon'
export {tiktokIcon} from './functions/tiktok-icon'
export {twitterIcon} from './functions/twitter-icon'
export {vkIcon} from './functions/vk-icon'
export {whatsappIcon} from './functions/whatsapp-icon'
export {xIcon} from './functions/x-icon'
export {youtubeIcon} from './functions/youtube-icon'

export {jsIcon} from './functions/js-icon'
