export {errorIcon} from './functions/error-icon'
export {linkedinIcon} from './functions/linkedin-icon'
export {telegramIcon} from './functions/telegram-icon'
export {instagramIcon} from './functions/instagram-icon'
export {facebookIcon} from './functions/facebook-icon'
export {okIcon} from './functions/ok-icon'
export {tiktokIcon} from './functions/tiktok-icon'
